////////////////////////////////////////////////////////////////////////////
// Original Code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "generated/AboutDialogBase.h"

namespace oura_charts
{

    class AboutDialog : public AboutDialogBase
    {
    public:
        // If you use this constructor, you must call Create(parent)
        AboutDialog() = default;  
        
        AboutDialog(wxWindow* parent);
    };

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************

}  // namespace oura_charts