////////////////////////////////////////////////////////////////////////////
// Original Code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "generated/MainFrameBase.h"

namespace oura_charts
{
    class MainFrame : public MainFrameBase
    {
    public:
        // If you use this constructor, you must call Create(parent)
        MainFrame() = default;
        MainFrame(wxWindow* parent) : MainFrameBase(parent) {};
    };


}  // namespace oura_charts