////////////////////////////////////////////////////////////////////////////
// Original Code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "generated/AboutDialogBase.h"
#include "oura_charts/UserProfile.h"


namespace oura_charts
{
   class AboutDialog : public AboutDialogBase
   {
   public:
      AboutDialog(const UserProfile& profile, wxWindow* parent);
      AboutDialog(const std::string& profile_text, wxWindow* parent);

   private:
      void Init(const std::string& profile_text, wxWindow* parent);
   };

}  // namespace oura_charts
