////////////////////////////////////////////////////////////////////////////
// Original Code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "generated/AboutDialogBase.h"
#include "oura_charts/UserProfile.h"


namespace oura_charts
{
    class AboutDialog : public AboutDialogBase
    {
    public:
        // If you use this constructor, you must call Create(parent)
        AboutDialog() = default;

        AboutDialog(const UserProfile& profile, wxWindow* parent);
        
        explicit AboutDialog(wxWindow* parent);
    };

}  // namespace oura_charts