////////////////////////////////////////////////////////////////////////////
// Original Code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "generated/AddDataFieldBase.h"

namespace oura_charts
{

   class AddDataFieldDialog : public oura_charts::AddDataFieldBase
   {
   public:
      AddDataFieldDialog(wxWindow* parent);

   protected:
   };


}
