////////////////////////////////////////////////////////////////////////////
// Original Code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
////////////////////////////////////////////////////////////////////////////

#pragma once

#include "generated/ChartOptionsBase.h"

class ChartOptionsCanvas : public oura_charts::ChartOptionsCanvas
{
public:
    ChartOptionsCanvas();  // If you use this constructor, you must call Create(parent)
    explicit ChartOptionsCanvas(wxWindow* parent);
};

