////////////////////////////////////////////////////////////////////////////
// Original Code generated by wxUiEditor
//
// The code is generated only once. You can now modify the code as needed.
////////////////////////////////////////////////////////////////////////////

#include "ChartOptionsCanvas.h"  // auto-generated: S:/repos/oura_charts/src/generated/ChartOptionsBase.h and S:/repos/oura_charts/src/generated/ChartOptionsBase.cpp

using namespace oura_charts;

ChartOptionsCanvas::ChartOptionsCanvas(wxWindow* parent) : ChartOptionsCanvas(parent) {}

// ************* End of generated code ***********
// DO NOT EDIT THIS COMMENT BLOCK!
//
// Code below this comment block will be preserved
// if the code for this class is re-generated.
//
// clang-format on
// ***********************************************
