# Generated by wxUiEditor -- see https://github.com/KeyWorksRW/wxUiEditor/
#
# DO NOT EDIT THIS FILE! Your changes will be lost if it is re-generated!

set (wx_generated_files

    ${CMAKE_CURRENT_LIST_DIR}/generated/AboutDialogBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/AddDataFieldBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/ChartOptionsBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/MainFrameBase.cpp
    ${CMAKE_CURRENT_LIST_DIR}/generated/PreferencesDialogBase.cpp

)
