name: Linux Clang Build
on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/.gitignore'


env:
  VCPKG_INSTALLATION_ROOT: "${{ github.workspace }}/vcpkg"
  PRESET_NAME: "linux-release"
  BUILD_DIR: "build/out/linux-release"


permissions:
  contents: write
  checks: write

jobs:
  linux_build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          sudo apt-get install -y cppcheck autoconf automake libtool pkg-config bison flex nasm libx11-dev libxft-dev libxext-dev libxrandr-dev

      - name: "Setup cmake/ninja"
        uses: lukka/get-cmake@latest

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: configure
        run: |
          cmake --preset=$PRESET_NAME

      - name: build
        run: |
          cmake --build --preset=$PRESET_NAME --target=all

      - name: tests
        run: |
          ctest --preset $PRESET_NAME --output-on-failure --output-junit "test_results.xml"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
            files: |
              ${{ env.BUILD_DIR }}/test_results.xml

