name: main-build
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions:
  contents: write
jobs:
  job:
    name: ${{ github.workflow }}
    runs-on: ubuntu-24.04

    env:
      VCPKG_INSTALLATION_ROOT: ${{ github.workspace }}/vcpkg
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/vcpkg/bincache
      VCPKG_DEFAULT_TRIPLET: "x64-linux"
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
      VCPKG_FEATURE_FLAGS: dependencygraph

    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: "Create directory '${{ env.VCPKG_DEFAULT_BINARY_CACHE }}'"
        run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        shell: bash

      # Setup the build machine with the most recent versions of CMake and Ninja. Both are cached if not already: on subsequent runs both will be quickly restored from GitHub cache service.
      - uses: lukka/get-cmake@latest

      - name: run-vcpkg
        uses: lukka/run-vcpkg@v11.5
        with:
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Build
        run: |
          scripts/build_preset.sh linux-release
