name: Windows MSVC Build
on:
  push:
    paths-ignore:
      - 'README.md'
      - '**/.gitignore'
  pull_request:
    branches:
      - main

env:
  VCPKG_INSTALLATION_ROOT: "${{ github.workspace }}\\vcpkg"
  PRESET_NAME: "win-release"
  BUILD_DIR: "build/out/win-release"

permissions:
  contents: write
  checks: write

jobs:
  windows_build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: 'Set vcvars'
      uses: ilammy/msvc-dev-cmd@v1

    - name: "Setup CMake/ninja"
      uses: lukka/get-cmake@latest

    - name: "Run Vcpkg"
      uses: lukka/run-vcpkg@v11.5
      with:
        vcpkgJsonGlob: '**/vcpkg.json'

    - name: Install winget
      uses: Cyberboss/install-winget@v1

    - name: Install pre-reqs
      run: |
        winget install CppCheck --verbose --disable-interactivity
        choco install OpenCppCoverage -y

    - name: configure
      run: |
        cmake --preset=$env:PRESET_NAME

    - name: build
      run: |
        cmake --build --preset=$env:PRESET_NAME --target=all

    - name: tests
      run: |
        ctest --preset $env:PRESET_NAME --output-on-failure --output-junit "test_results.xml"

    - name: Publish Test Artifacts
      uses: EnricoMi/publish-unit-test-result-action/windows@v2
      if: always()
      with:
          files: |
            ${{ env.BUILD_DIR }}/test_results.xml






